### ISSUE TITLE
Stuck at 4% of script

### ISSUE THREAD

**Issue by gjongeneel** [RenatoGregio/AzureResourceInventory#6]
This script sounds like a very useful tool. However, when I try the script within PowerShell Desktop to create an inventory (multiple Azure environments in which I'm both Global Administrator and Owner/Contributor), it hangs at '4% Complete, Starting Resources extraction jobs'. The script does not go beyond that step, even when I wait for a very long time. The logon is successful and if more than 1, I see a list of tenants from which I can choose, but after that the fun is over. There is no error displayed.

**Comment by ClaudioMerola** [comment]
Hi gjongeneel,

Have you tried to run the script as administrator? 

I think it might be strugling to install the Az Resource Graph extension. Your can also try to install the ImportExcel Module and the Az Graph extension manually before running the script.

Also, Are you running the last version of the script?

**Comment by gjongeneel** [comment]
Hi Claudio,

I tried the latest version (1.2.3) today and that works without any issue. I only get some warnings like 'WARNING: Failed adding PivotTable 'P2': Cannot index into a null array' but that is because some resources are not present within the subscription(s), e.g. in this case no Kubernetes. Great script and very useful. It does not seem to require Run as Administrator. Thanks!
